pipeline {
    agent any

    parameters {
        string(name: 'USER_EXTRA_PORTS',    defaultValue: '', description: 'UserService extra ports')
        string(name: 'PRODUCT_EXTRA_PORTS', defaultValue: '', description: 'ProductService extra ports')
        string(name: 'ORDER_EXTRA_PORTS',   defaultValue: '', description: 'OrderService extra ports')
		string(name: 'AUTH_EXTRA_PORTS',   defaultValue: '', description: 'AuthService extra ports')
    }

    stages {

        stage('Run EurekaServer-Pipeline') {
            steps {
                build job: 'EurekaServer-Pipeline', wait: true, propagate: true
            }
        }

        stage('Run ConfigServer-Pipeline') {
            steps {
                build job: 'ConfigServer-Pipeline', wait: true, propagate: true
            }
        }

        stage('Run UserService-Pipeline') {
            steps {
                build job: 'UserService-Pipeline',
                      parameters: [
                          string(name: 'EXTRA_PORTS', value: params.USER_EXTRA_PORTS)
                      ],
                      wait: true,
                      propagate: true
            }
        }

        stage('Run ProductService-Pipeline') {
            steps {
                build job: 'ProductService-Pipeline',
                      parameters: [
                          string(name: 'EXTRA_PORTS', value: params.PRODUCT_EXTRA_PORTS)
                      ],
                      wait: true,
                      propagate: true
            }
        }

        stage('Run OrderService-Pipeline') {
            steps {
                build job: 'OrderService-Pipeline',
                      parameters: [
                          string(name: 'EXTRA_PORTS', value: params.ORDER_EXTRA_PORTS)
                      ],
                      wait: true,
                      propagate: true
            }
        }
		
		stage('Run AuthService-Pipeline') {
            steps {
                build job: 'AuthService-Pipeline',
                      parameters: [
                          string(name: 'EXTRA_PORTS', value: params.AUTH_EXTRA_PORTS)
                      ],
                      wait: true,
                      propagate: true
            }
        }

        stage('Run ApiGateway-Pipeline') {
            steps {
                build job: 'ApiGateway-Pipeline', wait: true, propagate: true
            }
        }
    }

    post {
        always {
            echo "✅ Master Microservices Pipeline completed."
        }
    }
}
